Fantasy_Rosters = {
    "JohnBurrows_School": {
        "QB": ["Drake Maye"],
        "RB": ["Saquon Barkley", "Emari Demercado", "Kyren Williams", "Josh Jacobs"],
        "WR": [
            "Marvin Harrison Jr.",
            "George Pickens",
            "Travis Hunter",
            "Matthew Golden",
            "Jauan Jennings",
            "Wan'Dale Robinson",
            "Tre Tucker",
        ],
        "TE": ["Trey McBride"],
        "DST": ["Seahawks"],
        "K": ["Joshua Karty"],
    },
    "Kirkwood_Kittens": {
        "QB": ["Josh Allen", "J.J. McCarthy"],
        "RB": ["Jacory Croskey-Merritt", "D'Andre Swift"],
        "WR": [
            "Jaxon Smith-Njigba",
            "Nico Collins",
            "Hollywood Brown",
            "Jerry Jeudy",
            "Rashee Rice",
            "Xavier Legette",
            "Jayden Higgins",
            "Romeo Doubs",
        ],
        "TE": ["Travis Kelce"],
        "DST": ["Texans"],
        "K": ["Jake Bates"],
    },
    "Braeside_Bangers": {
        "QB": ["Jalen Hurts", "Baker Mayfield"],
        "RB": ["Derrick Henry", "James Cook", "Kenneth Gainwell", "Tyjae Spears (IR)"],
        "WR": [
            "Rashid Shaheed",
            "DeVonta Smith",
            "Christian Kirk",
            "Rome Odunze",
        ],
        "TE": ["Zach Ertz", "Jonnu Smith", "Darren Waller"],
        "DST": ["Giants", "Steelers"],
        "K": ["Brandon Aubrey"],
    },
    "The_Little_Stinkers": {
        "QB": ["Justin Fields", "Jaxson Dart"],
        "RB": [
            "Cam Skattebo",
            "RJ Harvey",
            "Jordan Mason",
            "Rico Dowdle",
            "Chuba Hubbard (IR)",
        ],
        "WR": [
            "Puka Nacua",
            "Garrett Wilson",
            "Emeka Egbuka",
            "Brian Thomas Jr.",
            "Chris Olave",
            "Elic Ayomanor",
        ],
        "TE": ["Brenton Strange", "George Kittle (IR)"],
        "DST": ["Cardinals"],
        "K": ["Tyler Loop"],
    },
    "KansasCity_Carnevores": {
        "QB": ["Kyler Murray", "Jayden Daniels"],
        "RB": [
            "Travis Etienne Jr.",
            "David Montgomery",
            "Bijan Robinson",
            "Tank Bigsby",
            "Rachaad White",
            "Jaylen Wright",
        ],
        "WR": ["Xavier Worthy", "Ricky Pearsall", "Cooper Kupp", "Mike Evans"],
        "TE": ["Sam LaPorta"],
        "DST": ["Vikings"],
        "K": ["Chase McLaughlin"],
    },
    "The_Lords_Force": {
        "QB": ["Dak Prescott", "Joe Burrow (IR)"],
        "RB": [
            "Ashton Jeanty",
            "Javonte Williams",
            "Bucky Irving",
            "Joe Mixon (IR)",
        ],
        "WR": [
            "Amon-Ra St. Brown",
            "Zay Flowers",
            "Jaylen Waddle",
            "Michael Pittman Jr.",
            "Keenan Allen",
            "Marvin Mims Jr.",
        ],
        "TE": ["David Njoku", "Kyle Pitts Sr."],
        "DST": ["Bills"],
        "K": ["Spencer Shrader", "Cairo Santos"],
    },
    "Dobis_PR": {
        "QB": ["Daniel Jones"],
        "RB": [
            "Jonathan Taylor",
            "Breece Hall",
            "TreVeyon Henderson",
            "Isiah Pacheco",
            "Woody Marks",
        ],
        "WR": [
            "Ja'Marr Chase",
            "Quentin Johnston",
            "Tetairoa McMillan",
            "Khalil Shakir",
            "Jordan Addison",
            "Cedric Tillman (IR)",
        ],
        "TE": ["Brock Bowers"],
        "DST": ["Chargers", "Patriots"],
        "K": ["Jason Myers"],
    },
    "KWood_Super_Marios": {
        "QB": ["Bo Nix", "Geno Smith"],
        "RB": [
            "Jahmyr Gibbs",
            "Kenneth Walker III",
            "Tyrone Tracy Jr.",
            "J.K. Dobbins",
            "Najee Harris (IR)",
            "Braelon Allen",
        ],
        "WR": [
            "Drake London",
            "Courtland Sutton",
            "Ladd McConkey",
            "Keon Coleman",
        ],
        "TE": ["Harold Fannin Jr."],
        "DST": ["Broncos"],
        "K": ["Harrison Butker"],
    },
    "Righteous_Gemstones": {
        "QB": ["C.J. Stroud", "Brock Purdy", "Caleb Williams"],
        "RB": ["De'Von Achane", "Rhamondre Stevenson", "Jerome Ford"],
        "WR": [
            "Davante Adams",
            "Jameson Williams",
            "Chris Godwin Jr.",
            "CeeDee Lamb",
            "Darnell Mooney",
            "Terry McLaurin (IR)",
            "Brandon Aiyuk (IR)",
        ],
        "TE": ["Jake Ferguson", "Juwan Johnson"],
        "DST": ["Lions"],
        "K": ["Jake Elliott"],
    },
    "Hinesward_Jersey": {
        "QB": ["Matthew Stafford", "Jordan Love", "Lamar Jackson (IR)"],
        "RB": ["Omarion Hampton", "Quinshon Judkins", "Chase Brown", "Jaylen Warren"],
        "WR": [
            "Stefon Diggs",
            "Justin Jefferson",
            "DJ Moore",
            "Troy Franklin",
            "Calvin Ridley",
            "Jayden Reed (IR)",
        ],
        "TE": ["Dalton Kincaid", "T.J. Hockenson"],
        "DST": ["Eagles"],
        "K": ["Cam Little"],
    },
    "BlueStreak_Bombers": {
        "QB": ["Patrick Mahomes", "Jared Goff"],
        "RB": [
            "Christian McCaffrey",
            "Alvin Kamara",
            "Trey Benson",
            "Sean Tucker",
            "Aaron Jones Sr. (IR)",
        ],
        "WR": [
            "Malik Washington",
            "Tee Higgins",
            "Deebo Samuel",
            "Rashod Bateman",
            "Tyreek Hill (IR)",
        ],
        "TE": ["Hunter Henry", "Mark Andrews", "Dallas Goedert"],
        "DST": ["Browns"],
        "K": ["Cameron Dicker"],
    },
    "Live_Laugh_Love": {
        "QB": ["Justin Herbert", "Tua Tagovailoa", "Jake Browning"],
        "RB": ["Tony Pollard", "Michael Carter", "Nick Chubb", "Brian Robinson Jr."],
        "WR": ["A.J. Brown", "Jakobi Meyers", "DK Metcalf", "Darius Slayton"],
        "TE": ["Tyler Warren", "Tucker Kraft"],
        "DST": ["Colts"],
        "K": ["Matt Prater"],
    },
}